import { jsPDF } from 'jspdf';
import { format, parseISO } from 'date-fns';
import { getStatus, getDaysUntil, formatCurrency, getNextRenewalDate } from './renewalUtils';

// ─── Color palette ────────────────────────────────────────────────────────────
const C = {
  primary:      [37,  99,  235],   // blue-600
  primaryLight: [219, 234, 254],   // blue-100
  primaryDark:  [29,  78,  216],   // blue-700
  emerald:      [5,   150, 105],   // emerald-600
  emeraldLight: [209, 250, 229],   // emerald-100
  amber:        [217, 119, 6],     // amber-600
  amberLight:   [254, 243, 199],   // amber-100
  red:          [220, 38,  38],    // red-600
  redLight:     [254, 226, 226],   // red-100
  gray900:      [17,  24,  39],
  gray700:      [55,  65,  81],
  gray500:      [107, 114, 128],
  gray400:      [156, 163, 175],
  gray200:      [229, 231, 235],
  gray100:      [243, 244, 246],
  gray50:       [249, 250, 251],
  white:        [255, 255, 255],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
function setFill(doc, rgb)   { doc.setFillColor(...rgb); }
function setDraw(doc, rgb)   { doc.setDrawColor(...rgb); }
function setTextColor(doc, rgb) { doc.setTextColor(...rgb); }
function setFont(doc, style = 'normal', size = 10) {
  doc.setFont('helvetica', style);
  doc.setFontSize(size);
}

function rect(doc, x, y, w, h, fill, draw) {
  if (fill) setFill(doc, fill);
  if (draw) setDraw(doc, draw);
  doc.rect(x, y, w, h, fill && draw ? 'FD' : fill ? 'F' : 'D');
}

function statusColors(status) {
  if (status === 'overdue')   return { bg: C.redLight,    text: C.red,     label: 'Overdue'   };
  if (status === 'due-today') return { bg: C.primaryLight, text: C.primary, label: 'Due Today' };
  if (status === 'upcoming')  return { bg: C.amberLight,  text: C.amber,   label: 'Upcoming'  };
  return                             { bg: C.emeraldLight, text: C.emerald, label: 'Active'    };
}

// Wrap text and return array of lines
function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(String(text || ''), maxWidth);
}

// ─── Page layout constants ────────────────────────────────────────────────────
const PAGE_W  = 210;
const PAGE_H  = 297;
const MARGIN  = 18;
const CONTENT = PAGE_W - MARGIN * 2;

// ─── Section header ───────────────────────────────────────────────────────────
function sectionHeader(doc, y, title, iconChar = '') {
  rect(doc, MARGIN, y, CONTENT, 8, C.primary);
  setFont(doc, 'bold', 9);
  setTextColor(doc, C.white);
  doc.text(`  ${iconChar}  ${title}`.trim(), MARGIN + 4, y + 5.5);
  return y + 8;
}

// ─── Two-column info row ──────────────────────────────────────────────────────
function infoRow(doc, y, label, value, highlight = false) {
  const rowH = 7.5;
  // Alternating row bg
  if (highlight) {
    rect(doc, MARGIN, y, CONTENT, rowH, C.gray50);
  }
  setFont(doc, 'bold', 9);
  setTextColor(doc, C.gray500);
  doc.text(label, MARGIN + 4, y + 5);
  setFont(doc, 'normal', 9);
  setTextColor(doc, C.gray900);
  const lines = wrapText(doc, value, CONTENT - 70);
  doc.text(lines, MARGIN + 68, y + 5);
  return y + rowH * lines.length;
}

// ─── Stat box ─────────────────────────────────────────────────────────────────
function statBox(doc, x, y, w, h, label, value, bgColor, textColor) {
  rect(doc, x, y, w, h, bgColor);
  setFont(doc, 'bold', 14);
  setTextColor(doc, textColor);
  doc.text(value, x + w / 2, y + h / 2 - 1, { align: 'center' });
  setFont(doc, 'normal', 8);
  setTextColor(doc, textColor);
  doc.text(label, x + w / 2, y + h / 2 + 5, { align: 'center' });
}

// ─── Page header (repeated on each page) ─────────────────────────────────────
function pageHeader(doc, renewal, pageNum, totalPages) {
  // Top bar
  rect(doc, 0, 0, PAGE_W, 22, C.primary);

  // Logo text
  setFont(doc, 'bold', 14);
  setTextColor(doc, C.white);
  doc.text('Tracksy', MARGIN, 14);

  // Subtitle
  setFont(doc, 'normal', 8);
  setTextColor(doc, [147, 197, 253]); // blue-300
  doc.text('Renewal Management Dashboard', MARGIN + 28, 14);

  // Right: report label
  setFont(doc, 'bold', 9);
  setTextColor(doc, C.white);
  doc.text('VENDOR REPORT', PAGE_W - MARGIN, 10, { align: 'right' });
  setFont(doc, 'normal', 8);
  setTextColor(doc, [147, 197, 253]);
  doc.text(`${renewal.name}  ·  Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, 16, { align: 'right' });
}

// ─── Page footer ─────────────────────────────────────────────────────────────
function pageFooter(doc, generatedAt) {
  const y = PAGE_H - 12;
  rect(doc, 0, y - 2, PAGE_W, 14, C.gray100);
  setDraw(doc, C.gray200);
  doc.line(0, y - 2, PAGE_W, y - 2);
  setFont(doc, 'normal', 7.5);
  setTextColor(doc, C.gray400);
  doc.text(`Generated by Tracksy  ·  ${generatedAt}`, MARGIN, y + 4);
  doc.text('Confidential — For internal use only', PAGE_W - MARGIN, y + 4, { align: 'right' });
}

// ─── Check if we need a new page ─────────────────────────────────────────────
function checkPage(doc, y, needed, renewal, generatedAt, pageRef) {
  if (y + needed > PAGE_H - 20) {
    pageFooter(doc, generatedAt);
    doc.addPage();
    pageRef.count += 1;
    pageHeader(doc, renewal, pageRef.count, '—');
    return 30;
  }
  return y;
}

// ─── Main PDF generator ───────────────────────────────────────────────────────
export function downloadReport(renewal, info, vendorFields = null, vendorEntries = null) {
  const doc          = new jsPDF({ unit: 'mm', format: 'a4' });
  const generatedAt  = format(new Date(), 'MMMM d, yyyy  ·  h:mm a');
  const status       = getStatus(renewal.renewalDate, renewal.purchaseDate);
  const days         = getDaysUntil(renewal.renewalDate);
  const nextDate     = getNextRenewalDate(renewal.renewalDate, renewal.billingCycle);
  const monthly      = renewal.billingCycle === 'monthly' ? renewal.amount : renewal.amount / 12;
  const yearly       = renewal.billingCycle === 'yearly'  ? renewal.amount : renewal.amount * 12;
  const sc           = statusColors(status);
  const pageRef      = { count: 1 };

  // ── PAGE 1 ──────────────────────────────────────────────────────────────────
  pageHeader(doc, renewal, 1, '—');

  let y = 30;

  // ── Hero block ───────────────────────────────────────────────────────────────
  rect(doc, MARGIN, y, CONTENT, 28, C.gray50);
  setDraw(doc, C.gray200);
  doc.rect(MARGIN, y, CONTENT, 28, 'D');

  // Avatar circle
  setFill(doc, C.primary);
  doc.circle(MARGIN + 14, y + 14, 10, 'F');
  setFont(doc, 'bold', 14);
  setTextColor(doc, C.white);
  doc.text(renewal.name[0].toUpperCase(), MARGIN + 14, y + 18, { align: 'center' });

  // Name & company
  setFont(doc, 'bold', 16);
  setTextColor(doc, C.gray900);
  doc.text(renewal.name, MARGIN + 28, y + 10);
  setFont(doc, 'normal', 9);
  setTextColor(doc, C.gray500);
  doc.text(info.fullName, MARGIN + 28, y + 17);
  setFont(doc, 'normal', 8);
  setTextColor(doc, C.gray400);
  doc.text(info.industry, MARGIN + 28, y + 23);

  // Status badge (right side)
  const badgeW = 28, badgeH = 7;
  const badgeX = PAGE_W - MARGIN - badgeW;
  rect(doc, badgeX, y + 5, badgeW, badgeH, sc.bg);
  setFont(doc, 'bold', 8);
  setTextColor(doc, sc.text);
  doc.text(sc.label, badgeX + badgeW / 2, y + 10, { align: 'center' });

  // Days pill
  const daysStr = days < 0 ? `${Math.abs(days)}d overdue` : days === 0 ? 'Due today' : `${days}d remaining`;
  const pillColor = days < 0 ? C.redLight : days <= 7 ? C.amberLight : C.emeraldLight;
  const pillText  = days < 0 ? C.red      : days <= 7 ? C.amber      : C.emerald;
  rect(doc, badgeX, y + 15, badgeW, badgeH, pillColor);
  setFont(doc, 'bold', 8);
  setTextColor(doc, pillText);
  doc.text(daysStr, badgeX + badgeW / 2, y + 20, { align: 'center' });

  y += 34;

  // ── 4 stat boxes ─────────────────────────────────────────────────────────────
  const boxW = (CONTENT - 9) / 4;
  const boxH = 20;
  const boxes = [
    { label: 'Monthly Cost',    value: formatCurrency(monthly),  bg: C.primaryLight, text: C.primary },
    { label: 'Annual Cost',     value: formatCurrency(yearly),   bg: C.emeraldLight, text: C.emerald },
    { label: 'Days Remaining',  value: days < 0 ? 'Overdue' : days === 0 ? 'Today' : `${days}`, bg: days < 0 ? C.redLight : days <= 7 ? C.amberLight : C.primaryLight, text: days < 0 ? C.red : days <= 7 ? C.amber : C.primary },
    { label: 'Billing Cycle',   value: renewal.billingCycle.charAt(0).toUpperCase() + renewal.billingCycle.slice(1), bg: C.emeraldLight, text: C.emerald },
  ];
  boxes.forEach((b, i) => {
    statBox(doc, MARGIN + i * (boxW + 3), y, boxW, boxH, b.label, b.value, b.bg, b.text);
  });
  y += boxH + 6;

  // ── Section 1: Vendor Identity ───────────────────────────────────────────────
  y = sectionHeader(doc, y, '1.  VENDOR IDENTITY');
  y += 1;
  const identityRows = [
    ['Service Name',   renewal.name],
    ['Legal Name',     info.fullName],
    ['Industry',       info.industry],
    ['Founded',        info.founded],
    ['Employees',      info.employees],
    ['Headquarters',   info.headquarters],
    ['Category',       renewal.category || '—'],
  ];
  identityRows.forEach((r, i) => { y = infoRow(doc, y, r[0], r[1], i % 2 === 0); });
  y += 5;

  // ── Section 2: Contact Information ──────────────────────────────────────────
  y = checkPage(doc, y, 40, renewal, generatedAt, pageRef);
  y = sectionHeader(doc, y, '2.  CONTACT INFORMATION');
  y += 1;
  const contactRows = vendorFields && vendorFields.length > 0
    ? vendorFields.map(f => [f.label, f.value || '—'])
    : [
        ['Website',        info.website],
        ['Support Email',  info.email],
        ['Phone',          info.phone],
      ];
  contactRows.forEach((r, i) => { y = infoRow(doc, y, r[0], r[1], i % 2 === 0); });
  y += 5;

  // ── Section 3: About ─────────────────────────────────────────────────────────
  y = checkPage(doc, y, 30, renewal, generatedAt, pageRef);
  y = sectionHeader(doc, y, '3.  ABOUT THIS SERVICE');
  y += 4;
  setFont(doc, 'normal', 9);
  setTextColor(doc, C.gray700);
  const descLines = wrapText(doc, info.description, CONTENT - 8);
  doc.text(descLines, MARGIN + 4, y);
  y += descLines.length * 5 + 5;

  // ── Section 4: Subscription Details ─────────────────────────────────────────
  y = checkPage(doc, y, 60, renewal, generatedAt, pageRef);
  y = sectionHeader(doc, y, '4.  SUBSCRIPTION DETAILS');
  y += 1;
  const subRows = [
    ['Billed Amount (USD)', `$${Number(renewal.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ...(renewal.amountInr != null ? [['Billed Amount (INR)', `Rs.${Number(renewal.amountInr).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`]] : []),
    ['Billing Cycle',    renewal.billingCycle.charAt(0).toUpperCase() + renewal.billingCycle.slice(1)],
    ['Contract Type',    info.contractType],
    ['Category',         renewal.category || '—'],
    ...(renewal.purchaseDate ? [['Purchase Date', format(parseISO(renewal.purchaseDate), 'MMMM d, yyyy')]] : []),
  ];
  subRows.forEach((r, i) => { y = infoRow(doc, y, r[0], r[1], i % 2 === 0); });

  // Cost breakdown sub-table
  y += 3;
  rect(doc, MARGIN, y, CONTENT, 6, C.gray200);
  setFont(doc, 'bold', 8);
  setTextColor(doc, C.gray700);
  doc.text('  COST BREAKDOWN (USD)', MARGIN + 4, y + 4.2);
  y += 6;

  const costRows = [
    ['Monthly',    `$${(monthly).toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ['Quarterly',  `$${(monthly * 3).toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ['Annual',     `$${(yearly).toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ['3-Year Est.', `$${(yearly * 3).toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
  ];
  costRows.forEach((r, i) => {
    if (i % 2 === 0) rect(doc, MARGIN, y, CONTENT, 7.5, C.gray50);
    setFont(doc, 'normal', 9);
    setTextColor(doc, C.gray500);
    doc.text(r[0], MARGIN + 4, y + 5);
    setFont(doc, 'bold', 9);
    setTextColor(doc, C.primary);
    doc.text(r[1], PAGE_W - MARGIN - 4, y + 5, { align: 'right' });
    y += 7.5;
  });
  y += 5;

  // ── Section 5: Renewal Schedule ──────────────────────────────────────────────
  y = checkPage(doc, y, 45, renewal, generatedAt, pageRef);
  y = sectionHeader(doc, y, '5.  RENEWAL SCHEDULE');
  y += 1;
  const renewalRows = [
    ['Current Status',        sc.label],
    ['Current Renewal Date',  format(parseISO(renewal.renewalDate), 'MMMM d, yyyy')],
    ['Upcoming Renewal',      format(nextDate, 'MMMM d, yyyy')],
    ['Days Until Renewal',    days < 0 ? `${Math.abs(days)} day(s) overdue` : days === 0 ? 'Due today' : `${days} day(s)`],
    ['Reminder Set',          `${renewal.reminderDays} day(s) before renewal`],
  ];
  renewalRows.forEach((r, i) => { y = infoRow(doc, y, r[0], r[1], i % 2 === 0); });
  y += 5;

  // ── Section 6: Service Level ─────────────────────────────────────────────────
  y = checkPage(doc, y, 30, renewal, generatedAt, pageRef);
  y = sectionHeader(doc, y, '6.  SERVICE LEVEL');
  y += 1;
  const slaRows = [
    ['Support Level', info.supportLevel],
    ['Uptime SLA',    info.uptime],
  ];
  slaRows.forEach((r, i) => { y = infoRow(doc, y, r[0], r[1], i % 2 === 0); });
  y += 5;

  // ── Section 7: Key Features ──────────────────────────────────────────────────
  if (info.features && info.features.length > 0) {
    y = checkPage(doc, y, 20 + info.features.length * 8, renewal, generatedAt, pageRef);
    y = sectionHeader(doc, y, '7.  KEY FEATURES');
    y += 3;
    const cols = 2;
    const colW = (CONTENT - 8) / cols;
    info.features.forEach((f, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const fx  = MARGIN + 4 + col * (colW + 4);
      const fy  = y + row * 8;
      // Chip background
      rect(doc, fx - 2, fy - 4, colW, 7, C.gray50);
      // Dot
      setFill(doc, C.emerald);
      doc.circle(fx + 2, fy - 0.5, 1.5, 'F');
      setFont(doc, 'normal', 8.5);
      setTextColor(doc, C.gray700);
      doc.text(f, fx + 6, fy);
    });
    y += Math.ceil(info.features.length / cols) * 8 + 5;
  }

  // ── Section 8: Notes ─────────────────────────────────────────────────────────
  if (renewal.notes) {
    y = checkPage(doc, y, 25, renewal, generatedAt, pageRef);
    y = sectionHeader(doc, y, '8.  NOTES');
    y += 4;
    rect(doc, MARGIN, y - 2, CONTENT, 14, C.gray50);
    setDraw(doc, C.gray200);
    doc.rect(MARGIN, y - 2, CONTENT, 14, 'D');
    setFont(doc, 'italic', 9);
    setTextColor(doc, C.gray700);
    const noteLines = wrapText(doc, renewal.notes, CONTENT - 10);
    doc.text(noteLines, MARGIN + 5, y + 4);
    y += 18;
  }

  // ── Section 9: Vendor History (if multiple entries) ───────────────────────
  if (vendorEntries && vendorEntries.length > 1) {
    y = checkPage(doc, y, 20 + vendorEntries.length * 12, renewal, generatedAt, pageRef);
    y = sectionHeader(doc, y, '9.  VENDOR HISTORY');
    y += 1;
    vendorEntries.forEach((entry, i) => {
      const dateStr = entry.createdAt || entry.created_at
        ? new Date(entry.createdAt || entry.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
        : '—';
      y = infoRow(doc, y, entry.name, dateStr, i % 2 === 0);
    });
    y += 5;
  }

  // ── Alert banner (if urgent) ─────────────────────────────────────────────────
  if (days < 0 || days <= 7) {
    y = checkPage(doc, y, 22, renewal, generatedAt, pageRef);
    y += 3;
    const alertBg   = days < 0 ? C.redLight   : C.amberLight;
    const alertText = days < 0 ? C.red        : C.amber;
    const alertMsg  = days < 0
      ? `This subscription is OVERDUE by ${Math.abs(days)} day(s). Immediate action required.`
      : days === 0
      ? 'This subscription is due for renewal TODAY. Please process immediately.'
      : `This subscription renews in ${days} day(s). Ensure payment is arranged.`;

    rect(doc, MARGIN, y, CONTENT, 14, alertBg);
    setDraw(doc, alertText);
    doc.setLineWidth(0.5);
    doc.rect(MARGIN, y, CONTENT, 14, 'D');
    doc.setLineWidth(0.2);

    setFont(doc, 'bold', 9);
    setTextColor(doc, alertText);
    doc.text('⚠  ATTENTION REQUIRED', MARGIN + 5, y + 6);
    setFont(doc, 'normal', 8.5);
    doc.text(alertMsg, MARGIN + 5, y + 11);
    y += 18;
  }

  // ── Final footer on last page ────────────────────────────────────────────────
  pageFooter(doc, generatedAt);

  // ── Fix page count on all pages ──────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    // Overwrite page number area
    rect(doc, PAGE_W - MARGIN - 55, 12, 55, 6, C.primary);
    setFont(doc, 'normal', 8);
    setTextColor(doc, [147, 197, 253]);
    doc.text(`${renewal.name}  ·  Page ${p} of ${totalPages}`, PAGE_W - MARGIN, 16, { align: 'right' });
  }

  // ── Save ─────────────────────────────────────────────────────────────────────
  const filename = `${renewal.name.replace(/\s+/g, '_')}_Vendor_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(filename);
}

// ─── CSV Export ───────────────────────────────────────────────────────────────
const CSV_COLUMNS = ['name', 'vendor', 'amount', 'billingCycle', 'renewalDate', 'status', 'category', 'notes'];

function escapeCSV(value) {
  const str = String(value ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function generateCSV(renewals) {
  const header = CSV_COLUMNS.join(',');
  if (!renewals || renewals.length === 0) {
    return header;
  }
  const rows = renewals.map(r => {
    const status = getStatus(r.renewalDate, r.purchaseDate);
    return CSV_COLUMNS.map(col => {
      if (col === 'status') return escapeCSV(status);
      return escapeCSV(r[col]);
    }).join(',');
  });
  return [header, ...rows].join('\n');
}

export function downloadCSV(renewals) {
  const csv = generateCSV(renewals);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `renewals_${format(new Date(), 'yyyy-MM-dd')}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ─── PDF List Export ──────────────────────────────────────────────────────────
export function downloadPDFReport(renewals) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const generatedAt = format(new Date(), 'MMMM d, yyyy  ·  h:mm a');

  // Header bar
  rect(doc, 0, 0, PAGE_W, 22, C.primary);
  setFont(doc, 'bold', 14);
  setTextColor(doc, C.white);
  doc.text('Tracksy', MARGIN, 14);
  setFont(doc, 'normal', 8);
  setTextColor(doc, [147, 197, 253]);
  doc.text('Renewals Export Report', MARGIN + 28, 14);
  setFont(doc, 'bold', 9);
  setTextColor(doc, C.white);
  doc.text(`Generated: ${generatedAt}`, PAGE_W - MARGIN, 14, { align: 'right' });

  let y = 30;

  // Summary section
  const total = renewals.length;
  const monthlySpend = renewals.reduce((sum, r) => {
    if (r.billingCycle === 'monthly') return sum + (r.amount || 0);
    if (r.billingCycle === 'yearly') return sum + (r.amount || 0) / 12;
    return sum;
  }, 0);
  const overdue = renewals.filter(r => getStatus(r.renewalDate, r.purchaseDate) === 'overdue').length;

  y = sectionHeader(doc, y, 'SUMMARY');
  y += 1;
  y = infoRow(doc, y, 'Total Renewals', String(total), true);
  y = infoRow(doc, y, 'Monthly Spend', formatCurrency(monthlySpend), false);
  y = infoRow(doc, y, 'Overdue', String(overdue), true);
  y += 6;

  // Renewals table
  if (renewals.length === 0) {
    y = sectionHeader(doc, y, 'RENEWALS');
    y += 6;
    setFont(doc, 'italic', 9);
    setTextColor(doc, C.gray500);
    doc.text('No renewals to display.', MARGIN + 4, y);
  } else {
    y = sectionHeader(doc, y, 'RENEWALS');
    y += 1;

    // Table header
    const cols = [
      { label: 'Name',         x: MARGIN,      w: 40 },
      { label: 'Vendor',       x: MARGIN + 40, w: 35 },
      { label: 'Amount',       x: MARGIN + 75, w: 25 },
      { label: 'Cycle',        x: MARGIN + 100, w: 20 },
      { label: 'Renewal Date', x: MARGIN + 120, w: 30 },
      { label: 'Status',       x: MARGIN + 150, w: 24 },
    ];

    rect(doc, MARGIN, y, CONTENT, 7, C.gray200);
    setFont(doc, 'bold', 8);
    setTextColor(doc, C.gray700);
    cols.forEach(c => doc.text(c.label, c.x + 2, y + 5));
    y += 7;

    renewals.forEach((r, i) => {
      if (y + 8 > PAGE_H - 20) {
        // Footer
        const fy = PAGE_H - 12;
        rect(doc, 0, fy - 2, PAGE_W, 14, C.gray100);
        setFont(doc, 'normal', 7.5);
        setTextColor(doc, C.gray400);
        doc.text(`Generated by Tracksy  ·  ${generatedAt}`, MARGIN, fy + 4);
        doc.addPage();
        y = 20;
        // Repeat table header
        rect(doc, MARGIN, y, CONTENT, 7, C.gray200);
        setFont(doc, 'bold', 8);
        setTextColor(doc, C.gray700);
        cols.forEach(c => doc.text(c.label, c.x + 2, y + 5));
        y += 7;
      }

      if (i % 2 === 0) rect(doc, MARGIN, y, CONTENT, 7.5, C.gray50);
      const status = getStatus(r.renewalDate, r.purchaseDate);
      const sc = statusColors(status);

      setFont(doc, 'normal', 8);
      setTextColor(doc, C.gray900);
      doc.text(String(r.name || '').substring(0, 22), cols[0].x + 2, y + 5);
      doc.text(String(r.vendor || '').substring(0, 20), cols[1].x + 2, y + 5);
      setTextColor(doc, C.primary);
      doc.text(formatCurrency(r.amount || 0), cols[2].x + 2, y + 5);
      setTextColor(doc, C.gray700);
      doc.text(String(r.billingCycle || ''), cols[3].x + 2, y + 5);
      doc.text(String(r.renewalDate || ''), cols[4].x + 2, y + 5);
      setTextColor(doc, sc.text);
      doc.text(sc.label, cols[5].x + 2, y + 5);
      y += 7.5;
    });
  }

  // Footer
  const fy = PAGE_H - 12;
  rect(doc, 0, fy - 2, PAGE_W, 14, C.gray100);
  setFont(doc, 'normal', 7.5);
  setTextColor(doc, C.gray400);
  doc.text(`Generated by Tracksy  ·  ${generatedAt}`, MARGIN, fy + 4);
  doc.text('Confidential — For internal use only', PAGE_W - MARGIN, fy + 4, { align: 'right' });

  const filename = `renewals_report_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(filename);
}
